language: cpp

compiler:
    - clang
    - gcc

notifications:
    email:
        on_success: change
        on_failure: always

before_install:
    # install a newer cmake since at this time Travis only has version 2.8
    - yes | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq

install:
    - sudo apt-get install cmake

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - cmake --build .

